finish prompt script currently has to be executed by sourcing the script

diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -6,12 +6,20 @@ if [ $# -eq 1 ]; then
     echo "setting up git prompt"
     which git-prompt
     #if git-prompt script is availabe launch
+    if [ $? -eq 0 ]; then
+      source git-prompt
+    else
+      echo "cannot find git-prompt script make sure it is in your"
+      echo "path and executable \n"
+      exit 1
+    fi
     ;;
   default)
     echo "setting up default prompt"
+    export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
     ;;
   esac
 else
   echo "you must supply an arument to prompt\n"
-  echo "usage prompt (git | default) \n"
+  echo "usage source prompt (git | default) \n"
 fi
